<?php

// autoload.php @generated by scripts/fetch-vendor.mjs (no composer binary in sandbox)

$vendorDir = __DIR__;
$baseDir = dirname($vendorDir);

$psr4 = require $vendorDir . '/composer/autoload_psr4.php';
$psr0 = require $vendorDir . '/composer/autoload_psr0.php';
$classMap = require $vendorDir . '/composer/autoload_classmap.php';
$files = require $vendorDir . '/composer/autoload_files.php';

// sort prefixes longest-first so the most specific namespace wins
uksort($psr4, function ($a, $b) { return strlen($b) - strlen($a); });
uksort($psr0, function ($a, $b) { return strlen($b) - strlen($a); });

spl_autoload_register(function ($class) use ($psr4, $psr0, $classMap) {
    if (isset($classMap[$class])) {
        require $classMap[$class];
        return;
    }
    if ($class[0] === '\\') {
        $class = substr($class, 1);
    }
    // PSR-4: longest registered prefix that the class starts with
    foreach ($psr4 as $prefix => $dirs) {
        if (strncmp($class, $prefix, strlen($prefix)) === 0) {
            $rel = str_replace('\\', '/', substr($class, strlen($prefix))) . '.php';
            foreach ($dirs as $dir) {
                $file = $dir . '/' . $rel;
                if (is_file($file)) { require $file; return; }
            }
        }
    }
    // PSR-0: prefix stripped, then full-class fallback
    foreach ($psr0 as $prefix => $dirs) {
        foreach ($dirs as $dir) {
            if ($prefix !== '' && strncmp($class, $prefix, strlen($prefix)) === 0) {
                $rel = str_replace('\\', '/', substr($class, strlen($prefix))) . '.php';
                $file = $dir . '/' . $rel;
                if (is_file($file)) { require $file; return; }
            }
            $file = $dir . '/' . str_replace('\\', '/', $class) . '.php';
            if (is_file($file)) { require $file; return; }
        }
    }
});

foreach ($files as $file) {
    if (is_file($file)) require_once $file;
}

return $files; // satisfies tooling that reads the return value of vendor/autoload.php
